### ISSUE TITLE
O cadastro e edição de planos não funciona mais

### ISSUE THREAD

**Issue by VictorOtavio** [ctvoicer/tarifador-ui#4]

**Comment by VictorOtavio** [comment]
O problema foi corrigido juntamente com a issue #1.

**Comment by joaopauloctvoicer** [comment]
Cadastro:
- O cadastro está OK.

Edição:
- Está editando apenas o PRIMEIRO da lista.

**Comment by VictorOtavio** [comment]
> Edição:
> * Está editando apenas o PRIMEIRO da lista.

@jpaulo-ct, não consegui reproduzir o erro aqui. A edição parece normal pra mim.
